### ISSUE TITLE
Неверный пароль

### ISSUE THREAD

**Issue by NataliaAlferova** [NataliaAlferova/BDD#1]
1. Открыть страницу авторизации
2. В поле "Логин" ввести "vasya"
3. В поле "Пароль" ввести "qwerty123"
4.  Нажать кнопку "Продолжить"

ОР:
Переход на страницу верификации

ФР:
Неверно указан логин или пароль
<img width="725" alt="Screenshot 2022-04-26 at 12 31 50" src="https://user-images.githubusercontent.com/91593811/165284152-592d7395-a72d-434f-933c-abd2ba14bf99.png">

**Comment by andrew-pahomov** [comment]
Не могу подтвердить проблему. Прошу описать тестовое окружение.
